Packet logging #35
estcube/Telemetry-Forwarding-Client pull request #45
Opened 2020-10-01 19:49 UTC by teet71

closes #35

2020-10-01 22:42 UTC, Risto-R approved these changes

2020-10-02 18:04 UTC, nowittyusername requested changes

2020-10-02 18:04 UTC, nowittyusername commented on client/src/file_logger.py
> +        self.file_logger.handle(self._logger.makeRecord(None, logging.DEBUG, None, None, str(frame), None, None))
Please add a newline at the end of your file.
https://stackoverflow.com/questions/729692/why-should-text-files-end-with-a-newline/729795#729795

2020-10-04 20:26 UTC, nowittyusername approved these changes

2020-10-04 20:26 UTC, merged